# Recommending Data 

### A simple recommendation system is created in this notebook that helps in suggesting promotional offers to different customer segments.

## ---------------------------------------------------------------------------------

## 1. Importing Libraries

In [158]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

pd.set_option("display.max_column", None)

print("libraries are loaded successfully")

libraries are loaded successfully

## -----------------------------------------------------------------------------------

## 2. Loading cleaned Master Datest

In [159]:
master_data = pd.read_csv("../cleaned_data/master_data.csv")
print("Master file is loaded successfully")

Master file is loaded successfully

## ---------------------------------------------------------------------------------

## 3. Selecting Completed Offers

In [160]:
# Here are all the types of offers

completed_offers = master_data[master_data["event"] == "offer completed"]

completed_offers.head()

,person,event,value,time,offer_id,reward,channels,difficulty,duration,offer_type,id_x,gender,age,id_y,became_member_on,income
12658,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,{'offer_id': '2906b810c7d4411798c6938adc9daaa5...,0,2906b810c7d4411798c6938adc9daaa5,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,2906b810c7d4411798c6938adc9daaa5,M,42.0,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,20160117,96000.0
12672,fe97aa22dd3e48c8b143116a8403dd52,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,0,fafdcd668e3743c1bb461111dcafc2a4,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,fafdcd668e3743c1bb461111dcafc2a4,F,39.0,fe97aa22dd3e48c8b143116a8403dd52,20171217,67000.0
12679,629fc02d56414d91bca360decdfa9288,offer completed,{'offer_id': '9b98b8c7a33c4b65b9aebfe6a799e6d9...,0,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9,M,52.0,629fc02d56414d91bca360decdfa9288,20180605,72000.0
12692,676506bad68e4161b9bbaffeb039626b,offer completed,{'offer_id': 'ae264e3637204a6fb9bb56bc8210ddfd...,0,ae264e3637204a6fb9bb56bc8210ddfd,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,ae264e3637204a6fb9bb56bc8210ddfd,M,37.0,676506bad68e4161b9bbaffeb039626b,20170515,92000.0
12697,8f7dd3b2afe14c078eb4f6e6fe4ba97d,offer completed,{'offer_id': '4d5c57ea9a6940dd891ad53e9dbe8da0...,0,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0,M,48.0,8f7dd3b2afe14c078eb4f6e6fe4ba97d,20150903,62000.0

## ------------------------------------------------------------------------------

## 4. Creating Customer Offer Matrix

In [161]:
# Here rows are customers, columns are offers and values are how many times customer completed that offer

customer_offer_matrix = pd.crosstab(
    completed_offers["person"],
    completed_offers["offer_id"]
)

customer_offer_matrix.head()

offer_id,0b1e1539f2cc45b7b9fa7c272da2e1d7,2298d6c36e964ae4a3e7e9706d1fb8c2,2906b810c7d4411798c6938adc9daaa5,4d5c57ea9a6940dd891ad53e9dbe8da0,9b98b8c7a33c4b65b9aebfe6a799e6d9,ae264e3637204a6fb9bb56bc8210ddfd,f19421c1d4aa40978ebb69ca19b0e20d,fafdcd668e3743c1bb461111dcafc2a4
person,,,,,,,,
0009655768c64bdeb2e877511632db8f,0,0,1,0,0,0,1,1
0011e0d4e6b944f998e987f904e8c1e5,1,1,0,0,1,0,0,0
0020c2b971eb4e9188eac86d93036a77,0,0,0,1,0,0,0,2
0020ccbbb6d84e358d3414a3ff76cffd,0,1,0,0,1,0,1,0
003d66b6608740288d6cc97a6903f4f0,1,0,0,0,0,0,0,2

## --------------------------------------------------------------------------------

## 5. Creating Offer Similarity Matrix

In [162]:
# Using cosine similarity

offer_similarity = cosine_similarity(customer_offer_matrix.T)

offer_similarity_df = pd.DataFrame(
    offer_similarity,
    index = customer_offer_matrix.columns,
    columns = customer_offer_matrix.columns
)

offer_similarity_df.head()

offer_id,0b1e1539f2cc45b7b9fa7c272da2e1d7,2298d6c36e964ae4a3e7e9706d1fb8c2,2906b810c7d4411798c6938adc9daaa5,4d5c57ea9a6940dd891ad53e9dbe8da0,9b98b8c7a33c4b65b9aebfe6a799e6d9,ae264e3637204a6fb9bb56bc8210ddfd,f19421c1d4aa40978ebb69ca19b0e20d,fafdcd668e3743c1bb461111dcafc2a4
offer_id,,,,,,,,
0b1e1539f2cc45b7b9fa7c272da2e1d7,1.000000,0.219419,0.221936,0.219403,0.214115,0.225826,0.219162,0.222873
2298d6c36e964ae4a3e7e9706d1fb8c2,0.219419,1.000000,0.220693,0.208833,0.221002,0.208288,0.229770,0.243607
2906b810c7d4411798c6938adc9daaa5,0.221936,0.220693,1.000000,0.212810,0.221713,0.211631,0.215712,0.231448
4d5c57ea9a6940dd891ad53e9dbe8da0,0.219403,0.208833,0.212810,1.000000,0.212669,0.234783,0.202070,0.208892
9b98b8c7a33c4b65b9aebfe6a799e6d9,0.214115,0.221002,0.221713,0.212669,1.000000,0.213997,0.220908,0.227230

## ----------------------------------------------------------------------------------------

## 6. Checking Similar Offers

In [163]:
# This shows which of the the offers are most similar to the the selected offer

offer_id = customer_offer_matrix.columns[0]

offer_similarity_df[offer_id].sort_values(ascending=False).head()

offer_id
0b1e1539f2cc45b7b9fa7c272da2e1d7    1.000000
ae264e3637204a6fb9bb56bc8210ddfd    0.225826
fafdcd668e3743c1bb461111dcafc2a4    0.222873
2906b810c7d4411798c6938adc9daaa5    0.221936
2298d6c36e964ae4a3e7e9706d1fb8c2    0.219419
Name: 0b1e1539f2cc45b7b9fa7c272da2e1d7, dtype: float64

## -------------------------------------------------------------------------

## 7. Recommendation Function

In [164]:
def recommend_similar_offers(offer_id):
    similar_offers = offer_similarity_df[offer_id].sort_values(ascending=False)
    return similar_offers.head(5)

## -----------------------------------------------------------------------

## 8. Test Recommendation

In [165]:
recommend_similar_offers(customer_offer_matrix.columns[0])

offer_id
0b1e1539f2cc45b7b9fa7c272da2e1d7    1.000000
ae264e3637204a6fb9bb56bc8210ddfd    0.225826
fafdcd668e3743c1bb461111dcafc2a4    0.222873
2906b810c7d4411798c6938adc9daaa5    0.221936
2298d6c36e964ae4a3e7e9706d1fb8c2    0.219419
Name: 0b1e1539f2cc45b7b9fa7c272da2e1d7, dtype: float64

### Observation :-

### The selected offer has highest similarity with itself (1.0). The remaining offers show similarity scores around 0.22, this indicates that the customers who completed the selected offer also interacted with these offers. These offers can therefore be recommended as similar promotions.

## ---------------------------------------------------------------------------

## 9. Saving similarity matrix

In [166]:
offer_similarity_df.to_csv("../cleaned_data/offer_similarity_matrix.csv")

## ---------------------------------------------------------------------------------

# 11. Conclusion

### So we used a collaborative filtering recommendation approach as discussed in this module using completed offers. A customer-offer matrix was created and eventually cosine similarity was used to calculate the similarity between offers. Based on this, similar promotional offers can be recommended to the customers