# Customer Segmentation

### This Notebook mainly focuses on grouping customers into different segments according to age and income. The purpose is mainly to understand the customers and their behavior.

## ---------------------------------------------------------------------------------

## 1. Importing Libraries

In [108]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries loaded successfully")

Libraries loaded successfully

## -----------------------------------------------------------------------------------

## 2. Loading Master Dataset

In [109]:
master_data = pd.read_csv("../cleaned_data/master_data.csv")

print("Master data loaded successfully")

Master data loaded successfully

## -------------------------------------------------------------------------------------------

## 3. Select Customer Data

In [110]:
customers = master_data[["person", "gender", "age", "income"]].drop_duplicates()

customers.head()

                             person   gender   age    income
0  78afa995795e4d85b5d9ceeca43f5fef        F  75.0  100000.0
1  a03223e636434f42ac4c3df47e8bac43  Unknown  55.0   64000.0
2  e2127556f4f64592b11af22de27a7932        M  68.0   70000.0
3  8ec6ce2a7e7949b1bf142def7d0e0586  Unknown  55.0   64000.0
4  68617ca6246f4fbc85e91a2a49552598  Unknown  55.0   64000.0

## ---------------------------------------------------------------------------------------

## 4. Create Age Segments

In [111]:
# Creating new column defining them according to their age

def age_segment(age):
    if age < 35:
        return "Young"
    elif age < 60:
        return "Middle Age"
    else :
        return "Senior"

customers["age_segment"] = customers["age"].apply(age_segment)

customers.head()

                             person   gender   age    income age_segment
0  78afa995795e4d85b5d9ceeca43f5fef        F  75.0  100000.0      Senior
1  a03223e636434f42ac4c3df47e8bac43  Unknown  55.0   64000.0  Middle Age
2  e2127556f4f64592b11af22de27a7932        M  68.0   70000.0      Senior
3  8ec6ce2a7e7949b1bf142def7d0e0586  Unknown  55.0   64000.0  Middle Age
4  68617ca6246f4fbc85e91a2a49552598  Unknown  55.0   64000.0  Middle Age

## -------------------------------------------------------------------------------------

## 5. Age Segment Distribution

In [112]:
# Grouping the customers according to their age segment

customers["age_segment"].value_counts()

age_segment
Middle Age    8869
Senior        5875
Young         2256
Name: count, dtype: int64

## ----------------------------------------------------------------------------------------

## 6. Create Income Segments

In [113]:
# Creating new column defining them according to their income

def income_segment(income):
    if income < 50000:
        return "Low Income"
    elif income < 80000:
        return "Medium Income"
    else:
        return "High Income"
    
customers["income_segment"] = customers["income"].apply(income_segment)

customers.head()

,person,gender,age,income,age_segment,income_segment
0,78afa995795e4d85b5d9ceeca43f5fef,F,75.0,100000.0,Senior,High Income
1,a03223e636434f42ac4c3df47e8bac43,Unknown,55.0,64000.0,Middle Age,Medium Income
2,e2127556f4f64592b11af22de27a7932,M,68.0,70000.0,Senior,Medium Income
3,8ec6ce2a7e7949b1bf142def7d0e0586,Unknown,55.0,64000.0,Middle Age,Medium Income
4,68617ca6246f4fbc85e91a2a49552598,Unknown,55.0,64000.0,Middle Age,Medium Income

## -------------------------------------------------------------------------------------

## 7. Income Segment Distribution

In [114]:
# Grouping the customers according to their age segment

customers["income_segment"].value_counts()

income_segment
Medium Income    9502
Low Income       3781
High Income      3717
Name: count, dtype: int64

## -------------------------------------------------------------------------

## 8. Average Income by Age Segment

In [115]:
# Customers grouping by age based on their average income

customers.groupby("age_segment")["income"].mean()

age_segment
Middle Age    65371.293269
Senior        70505.361702
Young         50900.709220
Name: income, dtype: float64

## ------------------------------------------------------------------------------------

## 9. Average age by income segment

In [116]:
# Customers grouped by income based on their average age

customers.groupby("income_segment")["age"].mean()

income_segment
High Income      62.485338
Low Income       48.019307
Medium Income    53.903389
Name: age, dtype: float64

## ----------------------------------------------------------------------------

## 10. Customer Segment Summary

In [117]:
customers.groupby(["age_segment", "income_segment"]).size()

age_segment  income_segment
Middle Age   High Income       1712
             Low Income        1580
             Medium Income     5577
Senior       High Income       2005
             Low Income        1105
             Medium Income     2765
Young        Low Income        1096
             Medium Income     1160
dtype: int64

## ------------------------------------------------------------------------------

## 11. Saving Segmented Customer Data

In [118]:
customers.to_csv("../cleaned_data/customer_segments.csv")

print("Customer segments were saved successfully")

Customer segments were saved successfully

## ----------------------------------------------------------------------------------------

# Conclusion

### Using simple rule based conditions were customers segmented based on their age and income. These divisions eventually can help starbucks to understand different types of customer groups and support targeted promotional recommendation.